steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud projects add-iam-policy-binding binaracademy-408514 --member=user:bayuuabdur2903@gmail.com --role=roles/compute.viewer && \
    set -x && gcloud compute ssh instance-2 --zone=us-central1-a --command='/bin/sh /home/bayuuabdur2903/pull.sh'